### ISSUE TITLE
Driver signature though ReactOS program 

### ISSUE THREAD

**Issue by Carlos487** [Raggles/com0com#1]
Hi, thanks for bringing to com0com to github, maybe you should look for [ReactOS open source driver program](http://reactos.org/wiki/Driver_Signing) as a free alternative or are you using your own certificate for signing? 

Also as a fork maybe should be better to rename the project.

Anyways thanks and if you need any help fell free to ask me, I'm a .Net developer.

**Comment by Raggles** [comment]
I have my own code signing cert, the release here is signed with it.  Thanks for the info on the ReactOS program, I was not aware of that.
